### ISSUE TITLE
Add asynchronous orchestrating function

### ISSUE THREAD

**Issue by new-village** [new-village/umap_flask#22]
データ収集（GET）と登録（POST）を自動化する非同期処理の機能を実装する。
非同期処理の書き方については、[ここ](http://zentoo.hatenablog.com/entry/2016/06/13/045354)を参考にされたし。
```python:
import asyncio

async def hogehoge():
     pass

asyncio.ensure_future(hogehoge())
```

**Comment by New-Village** [comment]
非同期処理の書き方については、[ここ](http://zentoo.hatenablog.com/entry/2016/06/13/045354)を参考にされたし。

`import asyncio

async def hogehoge():
     pass

asyncio.ensure_future(hogehoge())`

**Comment by New-Village** [comment]
TODO:

- [ ] jobs prefixの作成
- [ ] /race/collect&from=YYYYMM API の作成（api_race_collector function）
- [ ] race_collector function の作成

**Comment by New-Village** [comment]
引数の取得方法
https://stackoverflow.com/questions/24892035/how-can-i-get-the-named-parameters-from-a-url-using-flask
